### PR TITLE
Use req.params[] instead of req[], which was removed in rack 3.1.0

### PR DESCRIPTION
**Pull request by emon**
use req.params[] instead of req[], which was removed in rack 3.1.0
https://github.com/rack/rack/pull/2183

the omniauth-identity worked with the following warning in rack 3.0.x
```
warning: Request#[] is deprecated and will be removed in a future version of Rack
```
However, omniauth-identity no longer works with an error in rack 3.1.x and needs to be fixed.

See also #116

### CODE REVIEW

**Comment by pboling** [comment]
Thanks!  Please rebase on latest master branch.

**Comment by pboling** [comment]
Is this a diplicate of #116

**Review by pboling — APPROVED** [review]
LGTM

**Comment by pboling** [comment]
Merging this because it passed the build on some Rubies.  Will fix the others at some point, or someone can send a PR.

**Comment by scott8803** [comment]
Any idea when this will be pushed into the wild?  My bundle keeps pulling 3.0.9 which I think is 3 years old.

**Comment by pboling** [comment]
I'll work on getting a release out.

**Comment by scott8803** [comment]
I don't think this is correct:

      option :locate_conditions, ->(req) { { model.auth_key => req.params['auth_key'] } }

I've have an error come back saying req does not have a params (Its seems to already be the params).

---------

I also seem to be getting a rack error (something like response[2]=...   []= no method for nil.  I have tried to trace this down and I can't see what's generating it.  Just know that master causes it and my personally patched version of 3.0.9 does not.  This seems to occur most on Register new user.

**Comment by pboling** [comment]
Thanks for the report.  What version of `rack` are you on?

**Comment by pboling** [comment]
@scott8803 This fix is for compatibility with Rack v3.1+.  Please check your rack version!

**Pull request merged**
